# Generated by Django 2.2.5 on 2020-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.IntegerField(default='09123456789', error_messages={'unique': 'A user with that username already exists.'}, unique=True),
        ),
    ]
